In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.__version__

'3.0.6'

In [3]:
df =pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [4]:
#Number of records
df.shape[0] #10000, 11)

10000

In [5]:
#Disntinct fuel type
df['fuel_type'].nunique()

3

In [6]:
#Missing values
df.isnull().value_counts().sum()

np.int64(10000)

In [7]:
# The maximum fuel efficiency of cars from Asia
df[df["origin"]=='Asia' ]["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [8]:
median = df["horsepower"].describe()['50%']
print(f"The median is {median}")

The median is 254.0

In [9]:
freq_value= df['horsepower'].value_counts(ascending= False).reset_index().max()['horsepower']

print(f"The frequent value in horsepower is {freq_value}")

The frequent value in horsepower is 334.0

In [10]:
#Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.

null_values = df['horsepower'].isnull().sum() #np.int64(877) null values
print(f"Null values: {null_values}")
df.loc[df['horsepower'].isnull(), 'horsepower'] = freq_value
null_values # check if all null values are gone

Null values: 877

np.int64(877)

In [11]:
#Recalculaitng the median
recalculated_median= df['horsepower'].describe()['50%']
print(f"The re-calculated median is {recalculated_median}")

The re-calculated median is 257.0

In [12]:
all_cars_from_Asia = df.loc[df.origin== 'Asia' , ['model_year', 'vehicle_weight']]
all_cars_from_Asia.head(7)

    model_year  vehicle_weight
2         1996            4240
6         1992            4310
8         1997            4230
10        1978            4420
15        2007            3950
16        2021            4750
22        2019            4450

In [13]:
X= np.array(all_cars_from_Asia.head(7))

print(X)

[[1996 4240]
 [1992 4310]
 [1997 4230]
 [1978 4420]
 [2007 3950]
 [2021 4750]
 [2019 4450]]

In [14]:
XTX= X.T @ X

In [15]:
#Invert
xtx_inverse= np.linalg.inv(XTX)

In [16]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [17]:
w= xtx_inverse @ X.T @ y

print(w.sum())

0.3691969690492686